routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
})->name('root');

Route::get('/apply', 'ApplicationsController@apply')->name('apply');


Route::get('/reports/beneficiaries', function () {
    return view('beneficiaries');
})->name('beneficiaries');

Route::get('/reports/disbursements', function () {
    return view('disbursements');
})->name('disbursements');

Route::get('/reports/disbursement-profile', function () {
    return view('disbursement-profile');
})->name('disbursement-profile');

Route::get('/reports/beneficiaries/profile', function () {
    return view('profile');
})->name('profile');

Route::get('/reports/paymentrequests/{paymentrequest}/generate', 'PaymentRequestController@generate')->name('paymentrequests.generate');



Route::get('dashboard', function () {
    return view('layouts.admin.dashboard');
})->name('admin');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users','UserController');

Route::resource('scholarships/batches','BatchesController')->except('show');

Route::resource('scholarships/types','ScholarshipTypesController')->except('show');

Route::get('scholarships/applications/{application}/download', 'ApplicationsController@downloadAll')->name('applications.downloadall');

Route::resource('scholarships/applications','ApplicationsController');

Route::resource('beneficiary/paymentrequests','PaymentRequestController');

Route::resource('beneficiary','Beneficiaries\BeneficiaryController');


//Route::resource('payments/paymentrequests','PaymentRequestController');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, UUID, HasRoles, SoftDeletes;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password','photo','fname','lname',
//        'username'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     *Mutator to encrypt passwords in model to avoid rewriting functions in other controllers
     *
     * @param $password
     */
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }

    /**
     * Defines relationship between user account and applications
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function applications(){
        return $this->hasOne(Applications::class, 'id');
    }

    /**
     * Defines relationship between user account and user details
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function userDetails(){
        return $this->hasOne(UserDetails::class, 'id');
    }

    /**
     * Defines relationship between user account and educational history
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function educationHistories(){
        return $this->hasMany(EducationHistory::class);
    }

    /**
     * Defines relationship between user account and employment history
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function employmentHistories(){
        return $this->hasMany(EmploymentHistory::class);
    }

    /**
     * Defines relationship between user account and contacts
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function contacts(){
        return $this->hasMany(Contacts::class);
    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::withTrashed()->with('roles')->where('id','!=','1')->paginate(50);

        return view('users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $roles = Role::pluck('name','id');
        return view('users.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        //rules for input validation
        $rules = [
//            'username' => ['required','string','max:255', 'unique:users'],
            'fname' => ['required','string','max:255'],
            'lname' => ['required','string','max:255'],
            'photo' => ['image','mimes:jpg,png,jpeg'],
            'email' => ['required','string','email','max:255', 'unique:users'],
            'password' => ['required','string','min:8','confirmed'],
            'role' => ['required','string','max:255','exists:roles,id'],
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return redirect('users/create')
                ->withErrors($validator)
                ->withInput();
        }

        $data = $request->except('role','isActive');

        if ($request->hasFile('photo') && $request->file('photo')->isValid()){
            $data['photo'] = $request->file('photo')->store('img/profile_photos');
        }else{
            $data['photo'] = "img/unknown.png";
        }

        $user = User::create($data);
        $user->assignRole( $request->role );

        return redirect()->route('users.index')->with('success', 'New User Account for, '. $user->fname
            .' created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, User $user)
    {
//        return view('users.edit', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::pluck('name','id');
        return view('users.edit', compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
//        dd($request);
        $rules = [
//            'username' => ['required','string','max:255', 'unique:users'],
            'fname' => ['required','string','max:255'],
            'lname' => ['required','string','max:255'],
            'photo' => ['image','mimes:jpg,png,jpeg'],
            'email' => ['required','string','email','max:255', 'unique:users,email,'.$user->id],
            'password' => ['nullable','string','min:8','confirmed'],
            'role' => ['required','string','max:255','exists:roles,id'],
        ];

        $validator = Validator::make($request->all(), $rules);


        if ($validator->fails()) {
            return redirect(route('users.edit',$user->id))
                ->withErrors($validator)
                ->withInput();

        }

/*        if ($request->filled('username')){
            $user->username = $request->username;
        }*/

        if ($request->filled('fname')){
            $user->fname = $request->fname;
        }
        if ($request->filled('lname')){
            $user->lname = $request->lname;
        }
        if ($request->hasFile('photo') && $request->file('photo')->isValid()){
//            Storage::delete('img/profile_photos/'.$user->photo);
            $user['photo'] = $request->file('photo')->store('img/profile_photos');
        }
        if ($request->filled('email') && $user->email != $request->email){
            $user->email = $request->email;
        }
        if ($request->filled('password')){
            $user->password = $request->password;
        }

        $user->syncRoles(array($request->role));

//        if (!$user->isDirty()){
//            return redirect()->route('users.index')->with('info', 'No changes made');
//        }

        $user->save();

        return redirect()->route('users.index')->with('success', 'User Account for '. $user->fname
            .' updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('layouts.admin.main')

@section('page_title')
    User Management
@endsection

@section('custom_css')

    <!-- Dropify -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/dropify/css/dropify.min.css') }}">
@endsection

@section('content')
    <div class="row small-spacing">
        <form data-toggle="validator" method="post" action="{{ route('users.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="col-md-3 col-xs-12">
                <div class="box-content bordered bordered-all primary margin-bottom-20">
                    <div class="profile-avatar">
                        <h4 class="box-title">Photo</h4>

                    </div>
                    <!-- /.box-content -->
                    <div class="profile-avatar has-feedback">
                        <input type="file" id="input-file-to-destroy" class="dropify" name="photo" data-allowed-formats="portrait square"
                               data-max-file-size="1M" data-max-height="450" data-error="Sorry, you can't leave this blank"  required/>
                        <p class="help margin-top-10">Only portrait or square images, 1M max and 450 max-height.</p>
                    </div>
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                    <div class="help-block with-errors"></div>
                    <!-- .profile-avatar -->
                </div>
                <!-- /.box-content bordered -->
            </div>

            <div class="col-md-7 col-xs-12">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box-content bordered bordered-all primary margin-bottom-20 ">
                            <h4 class="box-title">Create User</h4>
                            <!-- /.box-title -->

                                <div class="form-group has-feedback">
                                    <label for="inputFname" class="control-label">First Name</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-user ico"></i></span>
                                        <input type="text" pattern="^[_A-z]{1,}$" maxlength="15" class="form-control"
                                               id="inputFname" name="fname" placeholder="First Name" data-error="Sorry, you can't leave this blank"
                                               value="{{ old('fname') }}" required>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="form-group has-feedback">
                                    <label for="inputLname" class="control-label">Last Name</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-user ico"></i></span>
                                        <input type="text" pattern="^[_A-z]{1,}$" maxlength="15" class="form-control"
                                               id="inputLname" name="lname" placeholder="Last Name" data-error="Sorry, you can't leave this blank"
                                               value="{{ old('lname') }}" required>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                    <div class="help-block with-errors"></div>
                                </div>

                                <div class="form-group has-feedback">
                                    <label for="inputEmail" class="control-label">Email</label>
                                    <div class="input-group">
                                        <span class="input-group-addon">@</span>
                                        <input type="email" class="form-control" id="inputEmail" placeholder="Email"
                                               name="email" data-error="Bruh, that email address is invalid"
                                               value="{{ old('email') }}" required>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                    <div class="help-block with-errors"></div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="form-group col-sm-6">
                                            <label for="inputPassword" class="control-label">Password</label>

                                            <input type="password" data-minlength="6" class="form-control" id="inputPassword"
                                                   name="password" placeholder="Password"
                                                   value="{{ old('password') }}" required>
                                            <div class="help-block">Minimum of 6 characters</div>
                                        </div>
                                        <div class="form-group col-sm-6">
                                            <label for="inputPasswordConfirm" class="control-label">Confirm Password</label>

                                            <input type="password" class="form-control" id="inputPasswordConfirm"
                                                   data-match="#inputPassword" data-match-error="Whoops, these don't match"
                                                   name="password_confirmation" placeholder="Confirm" value="{{ old('password_confirm') }}" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="user-role">User Role</label>
                                    <select id="user-role" class="form-control" name="role" >
                                        <option value="">Select Role</option>
                                        @foreach ($roles as $key => $value)
                                            <option value="{{ $key }}" {{ old('role') == $key ? 'selected' : ''}}>{{ $value }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <div class="checkbox">
                                        <input type="checkbox" id="terms" name="isActive" data-error="Leaving account disabled? User can't login" value="{{ old('isActive[0]') }}">
                                        <label for="terms">Activate account</label>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                </div>

                        </div>
                        <!-- /.box-content card -->
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </form>

    </div>
@endsection

@section('scripts')
    <!-- Dropify -->
    <script src="{{ asset('assets/plugin/dropify/js/dropify.min.js') }}"></script>
    <script src="{{ asset('assets/scripts/fileUpload.demo.min.js') }}"></script>

    <!-- Validator -->
    <script src="{{ asset('assets/plugin/validator/validator.min.js') }}"></script>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.admin.main')

@section('page_title')
    Edit User
@endsection

@section('custom_css')

    <!-- Dropify -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/dropify/css/dropify.min.css') }}">
@endsection

@section('content')
    <div class="row small-spacing">
        <form data-toggle="validator" method="POST" action="{{ route('users.update',$user->id) }}" enctype="multipart/form-data">
            @csrf
            {{ method_field('PATCH') }}
            <div class="col-md-3 col-xs-12">
                <div class="box-content bordered bordered-all primary margin-bottom-20">
                    <div class="profile-avatar">
                        <h4 class="box-title">Photo</h4>

                    </div>
                    <!-- /.box-content -->
                    <div class="profile-avatar has-feedback">
                        <input type="file" id="input-file-to-destroy" class="dropify" name="photo" data-allowed-formats="portrait square"
                               data-default-file="{{ old('photo', asset('storage/'.$user['photo'])) }}" data-max-file-size="1M" data-max-height="450" data-error="Sorry, you can't leave this blank" />
                        <p class="help margin-top-10">Only portrait or square images, 1M max and 450 max-height.</p>
                    </div>
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                    <div class="help-block with-errors"></div>
                    <!-- .profile-avatar -->
                </div>
                <!-- /.box-content bordered -->
            </div>

            <div class="col-md-7 col-xs-12">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box-content bordered bordered-all primary margin-bottom-20 ">
                            <h4 class="box-title">Create User</h4>
                            <!-- /.box-title -->

                            <div class="form-group has-feedback">
                                <label for="inputFname" class="control-label">First Name</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user ico"></i></span>
                                    <input type="text" pattern="^[_A-z]{1,}$" maxlength="15" class="form-control"
                                           id="inputFname" name="fname" placeholder="First Name" data-error="Sorry, you can't leave this blank"
                                           value="{{ old('fname',$user->fname )}}" required>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group has-feedback">
                                <label for="inputLname" class="control-label">Last Name</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user ico"></i></span>
                                    <input type="text" pattern="^[_A-z]{1,}$" maxlength="15" class="form-control"
                                           id="inputLname" name="lname" placeholder="Last Name" data-error="Sorry, you can't leave this blank"
                                           value="{{ old('lname',$user->lname) }}" required>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors"></div>
                            </div>

                            <div class="form-group has-feedback">
                                <label for="inputEmail" class="control-label">Email</label>
                                <div class="input-group">
                                    <span class="input-group-addon">@</span>
                                    <input type="email" class="form-control" id="inputEmail" placeholder="Email"
                                           name="email" data-error="Bruh, that email address is invalid"
                                           value="{{ old('email',$user->email)  }}" required>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors"></div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    <div class="form-group col-sm-6">
                                        <label for="inputPassword" class="control-label">Password</label>

                                        <input type="password" data-minlength="6" class="form-control" id="inputPassword"
                                               name="password" placeholder="Password"
                                               value="" >
                                        <div class="help-block">Minimum of 6 characters</div>
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <label for="inputPasswordConfirm" class="control-label">Confirm Password</label>

                                        <input type="password" class="form-control" id="inputPasswordConfirm"
                                               data-match="#inputPassword" data-match-error="Whoops, these don't match"
                                               name="password_confirmation" placeholder="Confirm" value="">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="user-role">User Role</label>
                                <select id="user-role" class="form-control" name="role" >
                                    <option value="">Select Role</option>
                                    @foreach ($roles as $key => $value)
                                        <option value="{{ $key }}" {{ old('role', isset($user->roles[0]->id)? $user->roles[0]->id : "" ) == $key ? 'selected' : ''}}>{{ $value }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <div class="checkbox">
                                    <input type="checkbox" id="terms" name="isActive" value="true" data-error="Leaving account disabled? User can't login"
                                    @if(old('isActive',!isset($user->deleted_at))) checked @endif>
                                    <label for="terms">Activate account</label>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                            </div>

                        </div>
                        <!-- /.box-content card -->
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </form>

    </div>
@endsection

@section('scripts')
    <!-- Dropify -->
    <script src="{{ asset('assets/plugin/dropify/js/dropify.min.js') }}"></script>
    <script src="{{ asset('assets/scripts/fileUpload.demo.min.js') }}"></script>

    <!-- Validator -->
    <script src="{{ asset('assets/plugin/validator/validator.min.js') }}"></script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.admin.main')

@section('page_title')
    User Management
@endsection

@section('content')
    <div class="row small-spacing">

        <div class="col-xs-12">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="box-content card" style="padding: 1%">
                        <form action="#" class="">
                            <div class="row form-horizontal">
                                <div class="col-lg-5 col-md-6 col-sm-12">
                                    <label for="user-type">User Type</label>
                                    <select id="user-type" class="form-control" name="type">
                                        <option value="0">All selected</option>
                                        <option value="1">Legacy Scholarship </option>
                                        <option value="2">10 Million Scholarship</option>
                                        <option value="3">TIAP Scholarship</option>
                                    </select>
                                </div>
                                <div class="col-lg-1 col-md-2 col-sm-3 " >
                                    <p> <br/></p>
                                    <button type="button"  class="btn btn-success waves-effect waves-light">Go</button>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-5 " >
                                    <p> <br/></p>
                                    <a  href="#" class="btn-icon btn-icon-left btn btn-info waves-effect waves-light"><i class="ico fa fa-user-plus"></i>Add User</a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-content card -->
                </div>
            </div>
        </div>
        <!-- /.col-xs-12 -->
    </div>
    <div class="row small-spacing">

        @if(isset($users))
            @foreach($users as $user)
                <div class="col-lg-3 col-md-6 col-xs-12">
                    <div class="box-content user-info">
                        <div class="avatar"><img src="{{ old('photo', asset('storage/'.$user['photo'])) }}" alt=""></div>
                        <!-- /.avatar -->
                        <div class="right-content">
                            <h4 class="name">{{$user->fname.' '.$user->lname}}</h4>
                            <!-- /.name -->
                            <p><a href="mailto:{{$user->email}}"></a>{{ $user->email }}</p>
                            <div class="text-warning small"></div>
                            <!-- /.text-warning -->
                        </div>
                        <div class="modal-footer" style="margin-top: 10%;padding-bottom: unset;text-align: left;">
                            <a href="{{route('users.edit',$user->id)}}" class="btn-icon btn-icon-left btn btn-primary btn-sm waves-effect waves-light text-white">
                                <i class="ico fa fa-pencil"></i>edit
                            </a>
                            <a href="#" class="btn-icon btn-icon-left btn btn-danger btn-sm waves-effect waves-light text-white" data-dismiss="modal">
                                <i class="ico fa fa-ban"></i>disable
                            </a>
                        </div>
                        <!-- /.right-content -->
                    </div>
            <!-- /.user-info -->
                </div>
            @endforeach
        @else
        //
        @endif
    </div>
@endsection