routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
})->name('root');

Route::get('/apply', 'ApplicationsController@apply')->name('apply');


Route::get('/reports/beneficiaries', function () {
    return view('beneficiaries');
})->name('beneficiaries');

Route::get('/reports/disbursements', function () {
    return view('disbursements');
})->name('disbursements');

Route::get('/reports/disbursement-profile', function () {
    return view('disbursement-profile');
})->name('disbursement-profile');

Route::get('/reports/beneficiaries/profile', function () {
    return view('profile');
})->name('profile');

Route::get('/reports/paymentrequests/{paymentrequest}/generate', 'PaymentRequestController@generate')->name('paymentrequests.generate');



Route::get('dashboard', function () {
    return view('layouts.admin.dashboard');
})->name('admin');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users','UserController');

Route::resource('scholarships/batches','BatchesController')->except('show');

Route::resource('scholarships/types','ScholarshipTypesController')->except('show');

Route::get('scholarships/applications/{application}/download', 'ApplicationsController@downloadAll')->name('applications.downloadall');

Route::resource('scholarships/applications','ApplicationsController');

Route::resource('beneficiary/paymentrequests','PaymentRequestController');

Route::resource('beneficiary','Beneficiaries\BeneficiaryController');


//Route::resource('payments/paymentrequests','PaymentRequestController');

app/Http/Controllers/ScholarshipTypesController.php
<?php

namespace App\Http\Controllers;

use App\ScholarshipTypes;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ScholarshipTypesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $scholarships = ScholarshipTypes::withTrashed()->get();
        return view('scholarshipTypes.index',compact('scholarships'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('scholarshipTypes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        //rules for input validation
        $rules = [
            'name' => ['required','string','max:255','unique:scholarship_types'],
            'description' => ['required','string'],
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return redirect()->route('types.create')
                ->withErrors($validator)
                ->withInput();
        }

        $scholarship = ScholarshipTypes::create($request->only('name','description'));

        if (!$request->filled('isActive')){
            $scholarship->delete();
        }

        return redirect()->route('types.index')->with('success', 'New Scholarship Type, '. $scholarship->name
        .' created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ScholarshipTypes  $scholarshipTypes
     * @return \Illuminate\Http\Response
     */
    public function show(ScholarshipTypes $scholarshipTypes)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ScholarshipTypes  $scholarshipTypes
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $scholarship = ScholarshipTypes::withTrashed()->findOrFail($id);
        return view('scholarshipTypes.edit',compact('scholarship'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ScholarshipTypes  $scholarshipTypes
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //rules for input validation
        $rules = [
            'name' => ['required','string','max:255','unique:scholarship_types,name,'.$id],
            'description' => ['required','string'],
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return redirect()->route('types.edit',$id)
                ->withErrors($validator)
                ->withInput();
        }

        $scholarship = ScholarshipTypes::withTrashed()->findOrFail($id);

        if($request->filled('name')){
            $scholarship->name = $request->name;
        }

        if ($request->filled('description')){
            $scholarship->description = $request->description;
        }

        if (($request->filled('isActive')) && ($scholarship->deleted_at != null) ){
            $scholarship->deleted_at = null;

        }elseif($scholarship->deleted_at == null && !$request->filled('isActive')){
            $scholarship->deleted_at = now();
        }

        if(!$scholarship->isDirty()){
            return redirect()->route('types.edit',$id)->with('info','No Changes Made To '.$scholarship->name);
        };

        $scholarship->save();
        return redirect()->route('types.index')->with('success', ''. $scholarship->name
            .' updated successfully.');
    }

    /**
     * disable, enable or Remove the specified resource from storage.
     *
     * @param  \App\ScholarshipTypes  $scholarshipTypes
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $type = ScholarshipTypes::withTrashed()->findOrFail($id);
        if($type->deleted_at != null){
            $type->restore();
            return redirect()->route('types.index')->with('info', 'Enabled scholarship type '. $type->name
                .'. New batches can now be created under this type again.');
        }

        if($type->batches()->exists()){
            $type->delete();
            return redirect()->route('types.index')->with('info', 'Disabled scholarship type '. $type->name
                .'. New batches cannot be created under this type anymore, existing batches will remain.');
        }

        $type->forceDelete();
        return redirect()->route('types.index')->with('success', 'scholarship type, '. $type->name
            .' deleted successfully.');
    }
}

resources/views/scholarshipTypes/create.blade.php
@extends('layouts.admin.main')

@section('page_title')
    Add New Scholarship Type
@endsection

@section('custom_css')

{{-- Dropify --}}
    <link rel="stylesheet" href="{{ asset('assets/plugin/dropify/css/dropify.min.css') }}">
@endsection

@section('content')
    <div class="row small-spacing">
        <form data-toggle="validator" method="post" action="{{ route('types.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="col-md-7 col-xs-12 ">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box-content bordered bordered-all primary margin-bottom-20 ">
                            <h4 class="box-title">New Scholarship Programme</h4>
                                {{--Scholarship Name--}}
                                <div class="form-group has-feedback">
                                    <label for="inputName" class="control-label">Scholarship Name</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-ticket ico"></i></span>
                                        <input type="text" pattern="^[_A-z]{1,}$" maxlength="15" class="form-control"
                                               id="inputName" name="name" placeholder="Name of New scholarship Programme" data-error="Sorry, you can't leave this blank"
                                               value="{{ old('name') }}" required>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                    <div class="help-block with-errors"></div>
                                </div>
                                {{--Scholarship Description--}}
                                <div class="form-group has-feedback">
                                    <label for="inputDescription" class="control-label">Description</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-edit ico"></i></span>
                                        <textarea type="text" class="form-control"
                                               id="inputDescription" name="description" placeholder=",
                                               Tell us about the new scholarship programme" data-error="Sorry, you can't leave this blank."
                                                  required>{{ old('description') }}</textarea>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                    <div class="help-block with-errors"></div>
                                </div>

                                <div class="form-group">
                                    <div class="checkbox">
                                        <input type="checkbox" id="terms" name="isActive" data-error="Leaving account disabled? User can't login" value="{{old('isActive',"active")}}">
                                        <label for="terms">Activate Programme</label>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                </div>

                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>
@endsection

@section('scripts')
{{-- Dropify --}}
    <script src="{{ asset('assets/plugin/dropify/js/dropify.min.js') }}"></script>
    <script src="{{ asset('assets/scripts/fileUpload.demo.min.js') }}"></script>

{{-- Validator --}}
    <script src="{{ asset('assets/plugin/validator/validator.min.js') }}"></script>
@endsection

resources/views/scholarshipTypes/edit.blade.php
@extends('layouts.admin.main')

@section('page_title')
    Edit Scholarship
@endsection

@section('custom_css')

{{-- Dropify --}}
    <link rel="stylesheet" href="{{ asset('assets/plugin/dropify/css/dropify.min.css') }}">
@endsection

@section('content')
    <div class="row small-spacing">
        <form data-toggle="validator" method="post" action="{{ route('types.update', $scholarship->id) }}" enctype="multipart/form-data">
            @csrf
            {{ method_field('PATCH') }}

            <div class="col-md-7 col-xs-12 ">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box-content bordered bordered-all primary margin-bottom-20 ">
                            <h4 class="box-title">New Scholarship Programme</h4>
                            {{--Scholarship Name--}}
                            <div class="form-group has-feedback">
                                <label for="inputName" class="control-label">Scholarship Name</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-ticket ico"></i></span>
                                    <input type="text" maxlength="15" class="form-control"
                                           id="inputName" name="name" placeholder="Name of New scholarchip Programme" data-error="Sorry, you can't leave this blank"
                                           value="{{ old('name', $scholarship->name) }}" required>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors"></div>
                            </div>
                            {{--Scholarship Description--}}
                            <div class="form-group has-feedback">
                                <label for="inputDescription" class="control-label">Description</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-edit ico"></i></span>
                                    <textarea type="text" class="form-control"
                                              id="inputDescription" name="description" placeholder=",
                                               Tell us about the new scholarship programme" data-error="Sorry, you can't leave this blank."
                                              required>{{ old('description',$scholarship->description) }}</textarea>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors"></div>
                            </div>

                            <div class="form-group">
                                <div class="checkbox">
                                    <input type="checkbox" id="terms" name="isActive" data-error="Leaving account disabled? User can't login" value="active" @if(!isset($scholarship->deleted_at)) checked @endif>
                                    <label for="terms">Activate Programme</label>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                <a href="{{route('types.index')}}" class="btn btn-danger waves-effect waves-light">Cancel</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

@section('scripts')
{{--  Dropify --}}
    <script src="{{ asset('assets/plugin/dropify/js/dropify.min.js') }}"></script>
    <script src="{{ asset('assets/scripts/fileUpload.demo.min.js') }}"></script>

{{-- Validator --}}
    <script src="{{ asset('assets/plugin/validator/validator.min.js') }}"></script>
@endsection

resources/views/scholarshipTypes/index.blade.php
@extends('layouts.admin.main')

@section('page_title')
    Scholarships
@endsection

@section('content')
    <div class="row small-spacing">

        <div class="col-xs-12">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="box-content card" style="padding: 1%">
                        <form action="#" class="">
                            <div class="row form-horizontal">
                                <div class="col-lg-2 col-md-2 col-sm-5 " >
                                    <a  href="{{ route('types.create') }}" class="btn-icon btn-icon-left btn btn-info waves-effect waves-light">
                                        <i class="ico fa fa-plus"></i>Add New Scholarship</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row small-spacing">

        @if(isset($scholarships))
            @foreach($scholarships as $scholarship)
                <div class="col-lg-4 col-md-6 col-xs-12">
                    <div class="box-content card">
                        <h4 class="box-title {{ $scholarship->deleted_at == null ? "bg-primary":"bg-danger"}}"><i class="ico fa fa-space-shuttle"></i>{{$scholarship->name}}</h4>
                        <div class="dropdown js__drop_down">
                            <a href="#" class="dropdown-icon glyphicon glyphicon-option-vertical js__drop_down_button"></a>
                            <ul class="sub-menu">
                                <form method="post" action="{{ route('types.destroy', $scholarship->id) }}">
                                    @method('delete')
                                    @csrf
                                    <li><button><a href="{{route('types.edit',$scholarship->id)}}">Edit</a></button></li>

                                    <li><button type="submit" ><a>{{ $scholarship->deleted_at==null? "Delete" : "Enable" }}</a></button></li>
                                </form>

                            </ul>
                        </div>
                        <div class="card-content">
                            <h4>Description:</h4>
                            <p>{{$scholarship->description}}</p>
                        </div>
                    </div>
                </div>
            @endforeach
        @else
        //
        @endif
    </div>
@endsection