routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
})->name('root');

Route::get('/apply', 'ApplicationsController@apply')->name('apply');


Route::get('/reports/beneficiaries', function () {
    return view('beneficiaries');
})->name('beneficiaries');

Route::get('/reports/disbursements', function () {
    return view('disbursements');
})->name('disbursements');

Route::get('/reports/disbursement-profile', function () {
    return view('disbursement-profile');
})->name('disbursement-profile');

Route::get('/reports/beneficiaries/profile', function () {
    return view('profile');
})->name('profile');

Route::get('/reports/paymentrequests/{paymentrequest}/generate', 'PaymentRequestController@generate')->name('paymentrequests.generate');



Route::get('dashboard', function () {
    return view('layouts.admin.dashboard');
})->name('admin');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users','UserController');

Route::resource('scholarships/batches','BatchesController')->except('show');

Route::resource('scholarships/types','ScholarshipTypesController')->except('show');

Route::get('scholarships/applications/{application}/download', 'ApplicationsController@downloadAll')->name('applications.downloadall');

Route::resource('scholarships/applications','ApplicationsController');

Route::resource('beneficiary/paymentrequests','PaymentRequestController');

Route::resource('beneficiary','Beneficiaries\BeneficiaryController');


//Route::resource('payments/paymentrequests','PaymentRequestController');

resources/views/layouts/admin/dashboard.blade.php
@extends('layouts.admin.main')

@section('page_title')
    Dashboard
@endsection

@section('content')
    <div class="row small-spacing">

        <div class="col-xs-12">
            <div class="box-content">
                <h4 class="box-title">Activity</h4>
                <!-- /.box-title -->
                <div class="dropdown js__drop_down">
                    <a href="#" class="dropdown-icon glyphicon glyphicon-option-vertical js__drop_down_button"></a>
                    <ul class="sub-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else there</a></li>
                        <li class="split"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                    <!-- /.sub-menu -->
                </div>
                <!-- /.dropdown js__dropdown -->
                <div id="smil-animation-index-chartist-chart" class="chartist-chart" style="height: 320px"></div>
                <!-- /#smil-animation-chartist-chart.chartist-chart -->
            </div>
            <!-- /.box-content -->
        </div>

        <div class="col-lg-3 col-md-6 col-xs-12">
            <div class="box-content">
                <h4 class="box-title">New Applications</h4>
                <!-- /.box-title -->
                <div class="dropdown js__drop_down">
                    <a href="#" class="dropdown-icon glyphicon glyphicon-option-vertical js__drop_down_button"></a>
                    <ul class="sub-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else there</a></li>
                        <li class="split"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                    <!-- /.sub-menu -->
                </div>
                <!-- /.dropdown js__dropdown -->
                <div class="content widget-stat">
                    <div class="percent bg-warning"><i class="fa fa-line-chart"></i>53%</div>
                    <!-- /.percent -->
                    <div class="right-content">
                        <h2 class="counter">837</h2>
                        <!-- /.counter -->
                        <p class="text">Applicants</p>
                        <!-- /.text -->
                    </div>
                    <!-- /.right-content -->
                    <div class="clear"></div>
                    <!-- /.clear -->
                    <div class="process-bar">
                        <div class="bar-bg bg-warning"></div>
                        <div class="bar js__width bg-warning" data-width="70%"></div>
                        <!-- /.bar js__width bg-success -->
                    </div>
                    <!-- /.process-bar -->
                </div>
                <!-- /.content widget-stat -->
            </div>
            <!-- /.box-content -->
        </div>

        <div class="col-lg-3 col-md-6 col-xs-12">
            <div class="box-content">
                <h4 class="box-title">Current Beneficiaries</h4>
                <!-- /.box-title -->
                <div class="dropdown js__drop_down">
                    <a href="#" class="dropdown-icon glyphicon glyphicon-option-vertical js__drop_down_button"></a>
                    <ul class="sub-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else there</a></li>
                        <li class="split"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                    <!-- /.sub-menu -->
                </div>
                <!-- /.dropdown js__dropdown -->
                <div class="content widget-stat-chart">
                    <div class="c100 p94 small green js__circle">
                        <span>92%</span>
                        <div class="slice">
                            <div class="bar"></div>
                            <div class="fill"></div>
                        </div>
                    </div>
                    <!-- /.c100 p58 -->
                    <div class="right-content">
                        <h2 class="counter">3922</h2>
                        <!-- /.counter -->
                        <p class="text">Awardees</p>
                        <!-- /.text -->
                    </div>
                    <!-- /.right-content -->
                </div>
                <!-- /.content -->
            </div>
            <!-- /.box-content -->
        </div>
        <!-- /.col-lg-3 col-md-6 col-xs-12 -->

        <!-- /.col-lg-3 col-md-6 col-xs-12 -->
        <div class="col-lg-3 col-md-6 col-xs-12">
            <div class="box-content">
                <h4 class="box-title">Fees Paid</h4>
                <!-- /.box-title -->
                <div class="dropdown js__drop_down">
                    <a href="#" class="dropdown-icon glyphicon glyphicon-option-vertical js__drop_down_button"></a>
                    <ul class="sub-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else there</a></li>
                        <li class="split"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                    <!-- /.sub-menu -->
                </div>
                <!-- /.dropdown js__dropdown -->
                <div class="content widget-stat">
                    <div class="percent bg-danger"><i class="fa fa-line-chart"></i>+40%</div>
                    <!-- /.percent -->
                    <div class="right-content">
                        <h2 class="counter">976</h2>
                        <!-- /.counter -->
                        <p class="text">Fees Paid This Month</p>
                        <!-- /.text -->
                    </div>
                    <!-- /.right-content -->
                    <div class="clear"></div>
                    <!-- /.clear -->
                    <div class="process-bar">
                        <div class="bar-bg bg-danger"></div>
                        <div class="bar js__width bg-danger" data-width="70%"></div>
                        <!-- /.bar js__width bg-success -->
                    </div>
                    <!-- /.process-bar -->
                </div>
                <!-- /.content widget-stat -->
            </div>
            <!-- /.box-content -->
        </div>
        <!-- /.col-lg-3 col-md-6 col-xs-12 -->
        <div class="col-lg-3 col-md-6 col-xs-12">
            <div class="box-content">
                <h4 class="box-title">Allowances Paid</h4>
                <!-- /.box-title -->
                <div class="dropdown js__drop_down">
                    <a href="#" class="dropdown-icon glyphicon glyphicon-option-vertical js__drop_down_button"></a>
                    <ul class="sub-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else there</a></li>
                        <li class="split"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                    <!-- /.sub-menu -->
                </div>
                <!-- /.dropdown js__dropdown -->
                <div class="content widget-stat-chart">
                    <div class="c100 p76 small blue js__circle">
                        <span>76%</span>
                        <div class="slice">
                            <div class="bar"></div>
                            <div class="fill"></div>
                        </div>
                    </div>
                    <!-- /.c100 p58 -->
                    <div class="right-content">
                        <h2 class="counter">804</h2>
                        <!-- /.counter -->
                        <p class="text">Beneficiaries Paid</p>
                        <!-- /.text -->
                    </div>
                    <!-- /.right-content -->
                </div>
                <!-- /.content -->
            </div>
            <!-- /.box-content -->
        </div>
        <!-- /.col-lg-3 col-md-6 col-xs-12 -->

        <div class="col-lg-4 col-xs-12">
            <div class="box-content">
                <h4 class="box-title">Statistics</h4>
                <!-- /.box-title -->
                <div class="dropdown js__drop_down">
                    <a href="#" class="dropdown-icon glyphicon glyphicon-option-vertical js__drop_down_button"></a>
                    <ul class="sub-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else there</a></li>
                        <li class="split"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                    <!-- /.sub-menu -->
                </div>
                <!-- /.dropdown js__dropdown -->
                <div class="content">
                    <div id="chart-2" class="js__chart" data-type="column"
                         data-chart="'Year'/'Statistics' | '2010'/75 | '2011'/42 | '2012'/75 | '2013'/38 | '2014'/19 | '2015'/93 "></div>
                </div>
                <!-- /.content -->
            </div>
            <!-- /.box-content -->
        </div>
        <!-- /.col-lg-4 col-md-12 -->

        <div class="col-lg-4 col-xs-12">
            <div class="box-content">
                <h4 class="box-title">Total Projects</h4>
                <!-- /.box-title -->
                <div class="dropdown js__drop_down">
                    <a href="#" class="dropdown-icon glyphicon glyphicon-option-vertical js__drop_down_button"></a>
                    <ul class="sub-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else there</a></li>
                        <li class="split"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                    <!-- /.sub-menu -->
                </div>
                <!-- /.dropdown js__dropdown -->
                <div class="content">
                    <div id="chart-3" class="js__chart" data-type="curve"
                         data-chart="'Year'/'Desktop'/'Mobile' | '2008'/53/0 | '2009'/35/73 | '2010'/89/14 | '2011'/50/50 | '2012'/86/37 | '2013'/47/89 | '2014'/75/50 | '2015'/100/70 "></div>
                </div>
                <!-- /.content -->
            </div>
            <!-- /.box-content -->
        </div>
        <!-- /.col-lg-4 col-md-12 -->

        <div class="col-lg-4 col-xs-12">
            <div class="box-content">
                <h4 class="box-title">Total Disbursement</h4>
                <!-- /.box-title -->
                <div class="dropdown js__drop_down">
                    <a href="#" class="dropdown-icon glyphicon glyphicon-option-vertical js__drop_down_button"></a>
                    <ul class="sub-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else there</a></li>
                        <li class="split"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                    <!-- /.sub-menu -->
                </div>
                <!-- /.dropdown js__dropdown -->
                <div class="content">
                    <div id="chart-1" class="js__chart" data-type="donut"
                         data-chart="'Type'/'Number' | 'Legacy Scholarship beneficiaries'/50 | '10million Scholarship beneficiaries'/20 | '20th Anniversary beneficiaries'/20 |'Teacher Improvement Award Programme (TIAP)'/10"></div>
                </div>
                <!-- /.content -->
            </div>
            <!-- /.box-content -->
        </div>
        <!-- /.col-lg-4 col-xs-12 -->

    </div>
@endsection

resources/views/layouts/admin/head.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('page_title') | {{ config('app.name', 'MTN Foundation Scholarships') }}</title>

    <!-- Main Styles -->

    <link rel="stylesheet" href="{{ asset('assets/plugin/bootstrap/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugin/bootstrap/css/bootstrap-theme.css') }}">

    <link rel="stylesheet" href="{{ asset('assets/styles/style.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/styles/style-dark.min.css') }}">

    <!-- mCustomScrollbar -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/mCustomScrollbar/jquery.mCustomScrollbar.min.css') }}">

    <!-- Waves Effect -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/waves/waves.min.css') }}">

    <!-- Sweet Alert -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/sweet-alert/sweetalert.css') }}">

    <!-- Percent Circle -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/percircle/css/percircle.css') }}">

    <!-- Chartist Chart -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/chart/chartist/chartist.min.css') }}">

    <!-- FullCalendar -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/fullcalendar/fullcalendar.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugin/fullcalendar/fullcalendar.print.css') }}" media='print'>
    <link rel="stylesheet" href="{{ asset('assets/styles/color/yellow.min.css') }}">

    <style>
        .table > tbody > tr > td {
            vertical-align: middle;
        }
        td .avatar img {
            border: 3px solid #d7ecfb;
            -webkit-border-radius: 100%;
            -moz-border-radius: 100%;
            border-radius: 100%;
            transition: all 0.4s ease;
            -moz-transition: all 0.4s ease;
            -o-transition: all 0.4s ease;
            -ms-transition: all 0.4s ease;
            -webkit-transition: all 0.4s ease;
            max-width: 100px;
            margin-right: 5%;
        }
        form > li > button {
            background: inherit;
            border: none;
            margin: 0 auto;
        }
        form > li > button a:hover {
            color:#ea4335 ;
        }
    </style>
    {{--custom css--}}
    @yield('custom_css')
</head>

    @yield('body')

</html>

resources/views/layouts/admin/left-nav.blade.php
<div class="main-menu">
    <header class="header">
        <a href="{{route('root')}}" class="logo">MTN SCHOLARSHIPS</a>
        <button type="button" class="button-close fa fa-times js__menu_close"></button>
        <div class="user">
            <a href="#" class="avatar"><img src="http://placehold.it/80x80" alt=""><span class="status online"></span></a>
            <h5 class="name"><a href="{{route('profile')}}">EDWARD BRYAN</a></h5>
            <h5 class="position">Administrator</h5>
            <!-- /.name -->
            <div class="control-wrap js__drop_down">
                <i class="fa fa-caret-down js__drop_down_button"></i>
                <div class="control-list">
                    <div class="control-item"><a href="{{route('profile')}}"><i class="fa fa-user"></i> Profile</a></div>
                    <div class="control-item"><a href="#"><i class="fa fa-gear"></i> Settings</a></div>
                    <div class="control-item"><a href="#"><i class="fa fa-sign-out"></i> Log out</a></div>
                </div>
                <!-- /.control-list -->
            </div>
            <!-- /.control-wrap -->
        </div>
        <!-- /.user -->
    </header>
    <!-- /.header -->
    <div class="content">

        <div class="navigation">
            <h5 class="title">Navigation</h5>
            <!-- /.title -->
            <ul class="menu js__accordion">
                <li class="{{ isActiveRoute('/' ,'current active') }}">
                    <a class="waves-effect" href="{{ url('/') }}"><i class="menu-icon fa fa-home"></i><span>Dashboard</span></a>
                </li>
                <li class="{{ isActiveRoute('scholarships*' ,'current active') }}">
                    <a class="waves-effect parent-item js__control" href="#"><i
                            class="menu-icon fa fa-file-text"></i><span>Scholarships</span><span
                            class="menu-arrow fa fa-angle-down"></span></a>
                    <ul class="sub-menu js__content">
                        <li class="{{ isActiveRoute(array('scholarships/batches*')) }}"><a href="{{route('batches.index')}}">Manage Batches</a></li>
                        <li class="{{ isActiveRoute(array('scholarships/types','scholarships/types/create','scholarships/types/*/edit')) }}"><a href="{{route('types.index')}}">Scholarships Types</a></li>
                        <li class="{{ isActiveRoute('scholarships/applications/create') }}"><a href="{{route('applications.create')}}">New Application</a></li>
                        <li class="{{ isActiveRoute('scholarships/applications') }}"><a href="{{ route('applications.index') }}">Manage Applications</a></li>
                        {{--                        <li class="{{ isActiveRoute('scholarships/create') }}"><a href="#">Open Applications</a></li>--}}
                    </ul>
                    <!-- /.sub-menu js__content -->
                </li>

                <li class="{{ isActiveRoute('reports*' ,'current active') }}">
                    <a class="waves-effect parent-item js__control" href="#"><i
                            class="menu-icon fa fa-bar-chart"></i><span>Reports</span><span
                            class="menu-arrow fa fa-angle-down"></span></a>
                    <ul class="sub-menu js__content">
                        <li class="{{ isActiveRoute(array('reports/beneficiaries','reports/beneficiaries/profile')) }}"><a href="{{route('beneficiaries')}}">Beneficiaries</a></li>
                        <li class="{{ isActiveRoute('beneficiary/paymentrequests') }}"><a href="{{route('paymentrequests.index')}}">Payments Requests</a></li>
                        <li class="{{ isActiveRoute('reports/disbursements') }}"><a href="{{route('disbursements')}}">Disbursements</a></li>
{{--                        <li class="{{ isActiveRoute('reports/disbursments/allowances') }}"><a href="#">Allowances</a></li>--}}
{{--                        <li class="{{ isActiveRoute('reports/disbursments/fees') }}"><a href="#">Fees</a></li>--}}
                    </ul>
                    <!-- /.sub-menu js__content -->
                </li>
            </ul>
            <!-- /.menu js__accordion -->
            <!--<h5 class="title">Users</h5>-->
            <!-- /.title -->
            <ul class="menu js__accordion">
{{--                <li class="{{ Request::is('users') ? "current active" : '' }}">--}}
                <li class="{{ isActiveRoute('users*' ,'current active') }}">
                    <a class="waves-effect parent-item js__control" href="#"><i
                            class="menu-icon fa fa-users"></i><span>Users</span><span
                            class="menu-arrow fa fa-angle-down"></span></a>
                    <ul class="sub-menu js__content">
                        <li class="{{ isActiveRoute('users/create') }}"><a href="{{ route('users.create') }}">Add Users</a></li>
                        <li class="{{ isActiveRoute('users') }}"><a href="{{ route('users.index') }}">Manage Users</a></li>
                    </ul>
                    <!-- /.sub-menu js__content -->
                </li>
                <li class="{{ isActiveRoute('alerts','current active') }}">
                    <a class="waves-effect" href="#"><i class="menu-icon fa fa-code"></i><span>Alerts</span><span
                            class="notice notice-yellow">6</span></a>
                </li>
            </ul>
            <!-- /.menu js__accordion -->
        </div>
        <!-- /.navigation -->
    </div>
    <!-- /.content -->
</div>

resources/views/layouts/admin/main.blade.php
{{--Adding head--}}
@extends('layouts.admin.head')

{{--Body Start--}}
@section('body')
    <body>

    {{--Main navigation on left--}}
    @include('layouts.admin.left-nav')
    {{--fixed-navbar--}}
    <div class="fixed-navbar">
        <div class="pull-left">
            <button type="button" class="menu-mobile-button glyphicon glyphicon-menu-hamburger js__menu_mobile"></button>
            <h1 class="page-title">@yield('page_title')</h1>
            <!-- /.page-title -->
        </div>
        <!-- /.pull-left -->
        <div class="pull-right">
            <div class="ico-item">
                <a href="#" class="ico-item fa fa-search js__toggle_open" data-target="#searchform-header"></a>
                <form action="#" id="searchform-header" class="searchform js__toggle"><input type="search" placeholder="Search..." class="input-search"><button class="fa fa-search button-search" type="submit"></button></form>
                <!-- /.searchform -->
            </div>
            <!-- /.ico-item -->
            <div class="ico-item fa fa-arrows-alt js__full_screen"></div>
            <!-- /.ico-item fa fa-fa-arrows-alt -->
            <a href="#" class="ico-item pulse"><span class="ico-item fa fa-bell notice-alarm js__toggle_open" data-target="#notification-popup"></span></a>
            <a href="#" class="ico-item fa fa-power-off js__logout"></a>
        </div>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
        <!-- /.pull-right -->
    </div>
    {{--notification-popup--}}
    <div id="notification-popup" class="notice-popup js__toggle" data-space="75">
        <h2 class="popup-title">Your Notifications</h2>
        <!-- /.popup-title -->
        <div class="content">
            <ul class="notice-list">
                <li>
                    <a href="#">
                        <span class="avatar"><img src="http://placehold.it/128x128" alt=""></span>
                        <span class="name">Jennifer</span>
                        <span class="desc">Like your post: “Contact Form 7 Multi-Step”</span>
                        <span class="time">45 min</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="avatar"><img src="http://placehold.it/80x80" alt=""></span>
                        <span class="name">Michael Zenaty</span>
                        <span class="desc">Like your post: “Contact Form 7 Multi-Step”</span>
                        <span class="time">50 min</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="avatar"><img src="http://placehold.it/80x80" alt=""></span>
                        <span class="name">Simon</span>
                        <span class="desc">Like your post: “Facebook Messenger”</span>
                        <span class="time">1 hour</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="avatar bg-violet"><i class="fa fa-flag"></i></span>
                        <span class="name">Account Contact Change</span>
                        <span class="desc">A contact detail associated with your account has been changed.</span>
                        <span class="time">2 hours</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="avatar"><img src="http://placehold.it/80x80" alt=""></span>
                        <span class="name">Helen 987</span>
                        <span class="desc">Like your post: “Facebook Messenger”</span>
                        <span class="time">Yesterday</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="avatar"><img src="http://placehold.it/128x128" alt=""></span>
                        <span class="name">Denise Jenny</span>
                        <span class="desc">Like your post: “Contact Form 7 Multi-Step”</span>
                        <span class="time">Oct, 28</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="avatar"><img src="http://placehold.it/80x80" alt=""></span>
                        <span class="name">Thomas William</span>
                        <span class="desc">Like your post: “Facebook Messenger”</span>
                        <span class="time">Oct, 27</span>
                    </a>
                </li>
            </ul>
            <!-- /.notice-list -->
            <a href="#" class="notice-read-more">See more messages <i class="fa fa-angle-down"></i></a>
        </div>
        <!-- /.content -->
    </div>
    {{--wrapper for main content--}}
    <div id="wrapper">
        {{--main content--}}
        <div class="main-content">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
{{--            {{ $success = 'test' }}--}}
            @if(Session::has('success'))
            <div class="alert alert-success">
                <ul>
                        <li>{{ session('success') }}</li>
                </ul>
            </div>
            @endif

            @if(Session::has('info'))
            <div class="alert alert-info">
                <ul>
                        <li>{{ session('info') }}</li>
                </ul>
            </div>
            @endif
            @yield('content')
            {{--footer--}}
            <footer class="footer">
                <ul class="list-inline">
                    <li>{{ now()->year }} © MTN GHANA FOUNDATION.</li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Terms</a></li>
                    <li><a href="#">Help</a></li>
                </ul>
            </footer>
        </div>
    </div>


    <script src="{{ asset('assets/scripts/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/scripts/modernizr.min.js') }}"></script>
    <script src="{{ asset('assets/plugin/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/plugin/mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js') }}"></script>
    <script src="{{ asset('assets/plugin/nprogress/nprogress.js') }}"></script>
    <script src="{{ asset('assets/plugin/sweet-alert/sweetalert.min.js') }}"></script>
    <script src="{{ asset('assets/plugin/waves/waves.min.js') }}"></script>
    <!-- Full Screen Plugin -->
    <script src="{{ asset('assets/plugin/fullscreen/jquery.fullscreen-min.js') }}"></script>

    <!-- Percent Circle -->
    <script src="{{ asset('assets/plugin/percircle/js/percircle.js') }}"></script>

    <!-- Google Chart -->
    <script type="text/javascript" src="{{ asset('https://www.gstatic.com/charts/loader.js') }}"></script>

    <!-- Chartist Chart -->
    <script src="{{ asset('assets/plugin/chart/chartist/chartist.min.js') }}"></script>
    <script src="{{ asset('assets/scripts/chart.chartist.init.min.js') }}"></script>

    <!-- FullCalendar -->
    <script src="{{ asset('assets/plugin/moment/moment.js') }}"></script>
    <script src="{{ asset('assets/plugin/fullcalendar/fullcalendar.min.js') }}"></script>
    <script src="{{ asset('assets/scripts/fullcalendar.init.js') }}"></script>

    {{--Scripts Placed at the end of the document so the pages load faster--}}
    @yield('scripts')

    <script src="{{ asset('assets/scripts/main.js') }}"></script>
    </body>
@endsection
{{--Body End--}}