routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
})->name('root');

Route::get('/apply', 'ApplicationsController@apply')->name('apply');


Route::get('/reports/beneficiaries', function () {
    return view('beneficiaries');
})->name('beneficiaries');

Route::get('/reports/disbursements', function () {
    return view('disbursements');
})->name('disbursements');

Route::get('/reports/disbursement-profile', function () {
    return view('disbursement-profile');
})->name('disbursement-profile');

Route::get('/reports/beneficiaries/profile', function () {
    return view('profile');
})->name('profile');

Route::get('/reports/paymentrequests/{paymentrequest}/generate', 'PaymentRequestController@generate')->name('paymentrequests.generate');



Route::get('dashboard', function () {
    return view('layouts.admin.dashboard');
})->name('admin');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users','UserController');

Route::resource('scholarships/batches','BatchesController')->except('show');

Route::resource('scholarships/types','ScholarshipTypesController')->except('show');

Route::get('scholarships/applications/{application}/download', 'ApplicationsController@downloadAll')->name('applications.downloadall');

Route::resource('scholarships/applications','ApplicationsController');

Route::resource('beneficiary/paymentrequests','PaymentRequestController');

Route::resource('beneficiary','Beneficiaries\BeneficiaryController');


//Route::resource('payments/paymentrequests','PaymentRequestController');

resources/views/payments/requests/create.blade.php
@extends('layouts.beneficiary.main')

@section('page_title')
   Payment Request
@endsection

@section('custom_css')
    <!-- Datepicker -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/datepicker/css/bootstrap-datepicker.min.css') }}">
@endsection


@section('content')
    <div class="row small-spacing">
        <form data-toggle="validator" method="post" action="{{ route('paymentrequests.store') }}" enctype="multipart/form-data">
            @csrf

            <div class="col-md-7 col-xs-12">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box-content bordered bordered-all primary margin-bottom-20 ">
                            <h4 class="box-title">Request For Payment</h4>
                            <!-- /.box-title -->

                            <div class="form-group has-feedback">
                                <label for="inputTitle" class="control-label">Title</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user ico"></i></span>
                                    <input type="text" pattern="^[_A-z]{1,}(\w*|\s*|-|\d*)*" maxlength="30" class="form-control"
                                           id="inputLname" name="title" placeholder="title of request" data-error="Sorry, enter a valid value"
                                           value="{{ old('title') }}" required>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors">
                                    @if ($errors->has('title'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('title') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group has-feedback">
                                <label for="description" class="control-label">Enter description of payment request</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-edit"></i></span>
                                    <textarea id="description" class="form-control" name="description" maxlength="225" rows="2" data-error="This field is required"
                                              placeholder="This textarea has a limit of 225 chars.">{{old('description') }}</textarea>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors">
                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group has-feedback">
                                <label for="inputVendor" class="control-label">Vendor Institution</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user ico"></i></span>
                                    <input type="text" pattern="^[_A-z]{1,}(\w*|\s*|-|\d*)*" maxlength="30" class="form-control"
                                           id="inputVendor" name="vendor_institution" placeholder="name of vendor company." data-error="Sorry, you can't leave this blank"
                                           value="{{ old('vendor_institution') }}" required>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors">
                                    @if ($errors->has('vendor_institution'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('vendor_institution') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-sm-6 has-feedback">
                                    <label for="inputDateDue" class="control-label">Date Due</label>
                                    <div class="input-group datepicker" id="inputDateDue">
                                        <span class="input-group-addon"><i class="fa fa-calendar ico"></i></span>
                                        <input data-minlength="6" class="form-control" id="datepicker"
                                               name="date_due" placeholder="dd/mm/yyyy"
                                               value="{{ old('date_due') }}" required>
                                    </div>
                                    <div class="help-block with-errors" >
                                        @if ($errors->has('date_due'))
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('date_due') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group col-sm-6 has-feedback">
                                    <label for="inputAmount" class="control-label">Amount</label>
                                    <div class="input-group" id="inputAmount">
                                        <span class="input-group-addon"><i class="fa fa-money ico"></i></span>
                                        <input min="10" class="form-control"
                                               name="amount"
                                               value="{{ old('amount') }}" required>
                                    </div>
                                    <div class="help-block with-errors" >
                                        @if ($errors->has('amount'))
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('amount') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="form-group has-feedback">
                                <label for="exampleInputFile">Upload Supporting Document</label>
                                <input type="file" id="exampleInputFile" name="attached_document">
                                <p class="help-block">file size must not exceed 1MB.</p>
                                <div class="help-block with-errors" >
                                    @if ($errors->has('attached_document'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('attached_document') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                            </div>

                        </div>
                        <!-- /.box-content card -->
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </form>

    </div>
@endsection
@section('scripts')

    <!-- Datepicker -->
    <script src="{{ asset('assets/plugin/datepicker/js/bootstrap-datepicker.min.js') }}"></script>

    <!-- Validator -->
    <script src="{{ asset('assets/plugin/validator/validator.min.js') }}"></script>

    <!-- Demo Scripts -->
    <script src="{{ asset('assets/scripts/form.demo.js') }}"></script>
@endsection

resources/views/payments/requests/edit.blade.php
@extends('layouts.beneficiary.main')

@section('page_title')
   Edit Payment Request
@endsection

@section('custom_css')
    <!-- Datepicker -->
    <link rel="stylesheet" href="{{ asset('assets/plugin/datepicker/css/bootstrap-datepicker.min.css') }}">
@endsection


@section('content')
    <div class="row small-spacing">
        <form data-toggle="validator" method="post" action="{{ route('paymentrequests.update', $paymentrequest->id) }}" enctype="multipart/form-data">
            @csrf
            {{ method_field('PATCH') }}

            <div class="col-md-7 col-xs-12">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box-content bordered bordered-all primary margin-bottom-20 ">
                            <h4 class="box-title">Request For Payment</h4>
                            <!-- /.box-title -->

                            <div class="form-group has-feedback">
                                <label for="inputTitle" class="control-label">Title</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user ico"></i></span>
                                    <input type="text" pattern="^[_A-z]{1,}(\w*|\s*|-|\d*)*" maxlength="30" class="form-control"
                                           id="inputLname" name="title" placeholder="title of request" data-error="Sorry, enter a valid value"
                                           value="{{ old('title', $paymentrequest->title) }}" required>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors">
                                    @if ($errors->has('title'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('title') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group has-feedback">
                                <label for="description" class="control-label">Enter description of payment request</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-edit"></i></span>
                                    <textarea id="description" class="form-control" name="description" maxlength="225" rows="2" data-error="This field is required"
                                              placeholder="This textarea has a limit of 225 chars.">{{old('description',$paymentrequest->description) }}</textarea>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors">
                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group has-feedback">
                                <label for="inputVendor" class="control-label">Vendor Institution</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user ico"></i></span>
                                    <input type="text" pattern="^[_A-z]{1,}(\w*|\s*|-|\d*)*" maxlength="30" class="form-control"
                                           id="inputVendor" name="vendor_institution" placeholder="name of vendor company." data-error="Sorry, you can't leave this blank"
                                           value="{{ old('vendor_institution',$paymentrequest->vendor_institution) }}" required>
                                </div>
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                <div class="help-block with-errors">
                                    @if ($errors->has('vendor_institution'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('vendor_institution') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-sm-6 has-feedback">
                                    <label for="inputDateDue" class="control-label">Date Due</label>
                                    <div class="input-group datepicker" id="inputDateDue">
                                        <span class="input-group-addon"><i class="fa fa-calendar ico"></i></span>
                                        <input data-minlength="6" class="form-control" id="datepicker"
                                               name="date_due" placeholder="dd/mm/yyyy"
                                               value="{{ old('date_due',$paymentrequest->date_due->format('d/m/Y')) }}" required>
                                    </div>
                                    <div class="help-block with-errors" >
                                        @if ($errors->has('date_due'))
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('date_due') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group col-sm-6 has-feedback">
                                    <label for="inputAmount" class="control-label">Amount</label>
                                    <div class="input-group" id="inputAmount">
                                        <span class="input-group-addon"><i class="fa fa-money ico"></i></span>
                                        <input min="10" class="form-control"
                                               name="amount"
                                               value="{{ old('amount',$paymentrequest->amount) }}" required>
                                    </div>
                                    <div class="help-block with-errors" >
                                        @if ($errors->has('amount'))
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('amount') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="form-group has-feedback">
                                <label for="exampleInputFile">Upload Supporting Document</label>
                                <input type="file" id="exampleInputFile" name="attached_document">
                                <p class="help-block">file size must not exceed 1MB.</p>
                                <div class="help-block with-errors" >
                                    @if ($errors->has('attached_document'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('attached_document') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                            </div>

                        </div>
                        <!-- /.box-content card -->
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </form>

    </div>
@endsection
@section('scripts')

    <!-- Datepicker -->
    <script src="{{ asset('assets/plugin/datepicker/js/bootstrap-datepicker.min.js') }}"></script>

    <!-- Validator -->
    <script src="{{ asset('assets/plugin/validator/validator.min.js') }}"></script>

    <!-- Demo Scripts -->
    <script src="{{ asset('assets/scripts/form.demo.js') }}"></script>
@endsection

resources/views/payments/requests/index.blade.php
@extends('layouts.beneficiary.main')

@section('page_title')
    Payments
@endsection

@section('content')

    <div class="row small-spacing">
        <div class="col-lg-3 col-md-6 col-xs-12">
            <div class="box-content bg-success text-white">
                <div class="statistics-box with-icon">
                    <i class="ico small fa fa-usd"></i>
                    <p class="text text-white">PAID</p>
                    <h2 class="counter">1,256,525 </h2>
                </div>
                <p class="text margin-bottom-0" style="text-align: right;">756,525 Transactions</p>
            </div>
            <!-- /.box-content -->
        </div>

        <!-- /.col-lg-3 col-md-6 col-xs-12 -->
        <div class="col-lg-3 col-md-6 col-xs-12">
            <div class="box-content bg-warning text-white">
                <div class="statistics-box with-icon">
                    <i class="ico small fa fa-usd"></i>
                    <p class="text text-white">PENDING</p>
                    <h2 class="counter">2,637</h2>
                </div>
                <p class="text margin-bottom-0" style="text-align: right;">756,525 Transactions</p>
            </div>
            <!-- /.box-content -->
        </div>
        <!-- /.col-lg-3 col-md-6 col-xs-12 -->
        <div class="col-lg-3 col-md-6 col-xs-12">
            <div class="box-content bg-info text-white">
                <div class="statistics-box with-icon">
                    <i class="ico small fa fa-users"></i>
                    <p class="text text-white">BENEFICIARIES </p>
                    <h2 class="counter">6,382</h2>
                </div>
                <p class="text margin-bottom-0" style="text-align: right;">756,525 Transactions</p>
            </div>
            <!-- /.box-content -->
        </div>
        <!-- /.col-lg-3 col-md-6 col-xs-12 -->
        <div class="col-lg-3 col-md-6 col-xs-12">
            <div class="box-content bg-danger text-white">
                <div class="statistics-box with-icon">
                    <i class="ico small fa fa-usd"></i>
                    <p class="text text-white">FAILED</p>
                    <h2 class="counter">12,564</h2>
                </div>
                <p class="text margin-bottom-0" style="text-align: right;">756,525 Transactions</p>
            </div>
            <!-- /.box-content -->
        </div>

        <!-- /.col-lg-3 col-md-6 col-xs-12 -->
    </div>
    <!-- .row -->
    <div class="row small-spacing">

        <div class="col-xs-12">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="box-content card">
                        <div class="table-responsive table-purchases">
                            <table class="table table-striped margin-bottom-10">
                                <thead>
                                <tr>
                                    <th style="width:30%;">Transaction ID</th>
                                    <th>Vendor/ Institution</th>
                                    <th>Amount</th>
                                    <th>Date</th>
                                    <th>State</th>
                                    <th style="width:5%;"></th>
                                </tr>
                                </thead>
                                {{--
                                    "id" => "752024bb-4d1d-43f1-a8e1-d0003c6a5556"
                                    "title" => "A test request"
                                    "description" => "A test request description"
                                    "amount" => 2000.0
                                    "vendor_institution" => "AITI-KACE"
                                    "date_due" => "2019-07-31"
                                    "user_id" => "63cd2d39-4523-49cb-9744-a9c4cf286dc4"
                                    "attached_document" => "payment_requests//JxNRllvSCKXov5pITHTYQh6SKFLSUcrKlC1EdbXw.png"
                                    "status" => "pending"
                                    "deleted_at" => null
                                    "created_at" => "2019-07-25 11:38:33"
                                    "updated_at" => "2019-07-25 11:38:33"
                                    --}}
                                <tbody>
                                    @foreach ($paymentRequests as $paymentRequest)
                                    <tr>
                                            <td>{{$paymentRequest->id}}</td>
                                            <td>{{$paymentRequest->vendor_institution}}</td>
                                            <td>GHC {{$paymentRequest->amount}}</td>
                                            <td>{{$paymentRequest->date_due}}</td>
                                    <td class="{{$paymentRequest->statusColor()}}">{{$paymentRequest->status}}</td>
                                    <td><a href="{{route('paymentrequests.edit',$paymentRequest->id)}}"><i class="ico fa fa-pencil"></i></a></td>
                                    </tr>
                                    @endforeach
                               </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.box-content card -->
                </div>
            </div>
        </div>
        <!-- /.col-xs-12 -->
    </div>
@endsection